<?php 
$adminNo=$_GET['adminNo'];	
$_SESSION['adminNo']=$adminNo;	
		include '../connection/connect.php';
include '../common/functions.php'; 
			 $query1="SELECT s.adminNo, s.parent_id, p.email_address
FROM student_details s, parent_details p
WHERE s.parent_id = p.parent_id
AND s.adminNo =  '$adminNo' "; 
								
				$result = mysqli_query($con1,$query1)or die(mysqli_error($con1));
			
			$addr=mysqli_fetch_assoc($result);
			extract($addr);
	//include '../../index/send-email.php';		
$_SESSION['emailaddr']=$email_address;

			?>	
<?php
//session_start();
require 'class.phpmailer.php';

$mail = new PHPMailer();
$mail->IsSMTP();
$mail->Mailer = 'smtp';
$mail->SMTPAuth = true;
$mail->Host = 'smtp.gmail.com'; // "ssl://smtp.gmail.com" didn't worked
$mail->Port = 465;
$mail->SMTPSecure = 'ssl';
// or try these settings (worked on XAMPP and WAMP):
// $mail->Port = 587;
// $mail->SMTPSecure = 'tls';


$mail->Username = "martiniriga@gmail.com";
$mail->Password = "kandunya";


$mail->IsHTML(true); // if you are going to send HTML formatted emails
$mail->SingleTo = true; // if you want to send a same email to multiple users. multiple emails will be sent one-by-one.

$mail->From = "martiniriga@gmail.com";
$mail->FromName = "Pioneer Students Information System";
//echo $email_address;
//break;
$mail->addAddress($email_address,"Recipient");
//$mail->addAddress("miriga.ssanics@gmail.com","Wewe 2");

//$mail->addCC("user.3@ymail.com","User 3");
//$mail->addBCC("user.4@in.com","User 4");

$mail->Subject = "Students Transcript";
$mail->Body = "Hi,<br /><br />Thank you for trusting us with your education.<br>
<br> the link for your trancript click <a href='localhost/sms/modules/academics/transcript2.php?adminNo=$adminNo&mail=1'>here</a>
<br>Generated by Pioneer SIS.
";
$mail->SMTPDebug = 1;
if(!$mail->Send())
{
header('location: /sms/index.php?view=pre_reportCard&info=msgf');
echo "Message was not sent <br />PHPMailer Error: " . $mail->ErrorInfo;
}
    
else{
header('location: /sms/index.php?view=pre_reportCard&info=msgs');
    echo "Message has been sent to $eadd";
	}
?>	